import { Dispatch, SetStateAction, SyntheticEvent } from "react";

export interface CadastroContextProps {
  name: string;
  cpf: string;
  email: string;
  password: string;
  phone: string;
  birthdate: string;
  refFormRegister: React.RefObject<HTMLFormElement>;
  refInputName: React.RefObject<HTMLInputElement>;
  refInputCpf: React.RefObject<HTMLInputElement>;
  refInputEmail: React.RefObject<HTMLInputElement>;
  refInputPasssword: React.RefObject<HTMLInputElement>;
  refInputBirthdate: React.RefObject<HTMLInputElement>;
  refInputGenderMan: React.RefObject<HTMLInputElement>;
  refInputGenderWoman: React.RefObject<HTMLInputElement>;
  refInputGenderUninformed: React.RefObject<HTMLInputElement>;
  refInputPhone: React.RefObject<HTMLInputElement>;
  isNameError: string | HTMLInputElement;
  isCpfError: string | HTMLInputElement;
  isEmailError: string | HTMLInputElement;
  isPasswordError: string | HTMLInputElement;
  isGenderError: string | HTMLInputElement;
  isBirthdateError: string | HTMLInputElement;
  isPhoneError: string | HTMLInputElement;
  setNameError: Dispatch<SetStateAction<string | HTMLInputElement>>;
  setCpfError: Dispatch<SetStateAction<string | HTMLInputElement>>;
  setEmailError: Dispatch<SetStateAction<string | HTMLInputElement>>;
  setPasswordError: Dispatch<SetStateAction<string | HTMLInputElement>>;
  setGenderError: Dispatch<SetStateAction<string | HTMLInputElement>>;
  setBirthdateError: Dispatch<SetStateAction<string | HTMLInputElement>>;
  setPhoneError: Dispatch<SetStateAction<string | HTMLInputElement>>;
  handleValidateName: () => void;
  handleChangeName: (event: React.ChangeEvent<HTMLInputElement>) => void;
  handleValidateCpf: () => void;
  handleChangeCpf: (event: React.ChangeEvent<HTMLInputElement>) => void;
  handleValidateEmail: () => void;
  handleChangeEmail: (event: React.ChangeEvent<HTMLInputElement>) => void;
  handleValidatePassword: () => void;
  handleChangePassword: (event: React.ChangeEvent<HTMLInputElement>) => void;
  handleValidateGender: () => void;
  handleValidateBirthdate: () => void;
  handleChangeBirthdate: (event: React.ChangeEvent<HTMLInputElement>) => void;
  handleValidatePhone: () => void;
  handleChangePhone: (event: React.ChangeEvent<HTMLInputElement>) => void;
  handleSubmit: (event: SyntheticEvent) => void;
}
